import React, { useState } from "react";
import Head from "next/head";
import Header from "../../components/homepage/Header";
import Footer from "../../components/homepage/Footer";
import TabSwitch from "../../components/mentor_profile/TabSwitch";
import {
  Education,
  Work_experience,
} from "../../components/mentor_profile/tabInterfaces";

export default function Login() {
  return (
    <div className="!overflow-x-hidden w-[100vw]">
      <Head>
        <title>Profile </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header navTitle="MentorConnect" />

      {/**Banner */}
      <main className=" flex h-[90vh] w-[100vw] items-center justify-center border-red-500 bg-[#FAFAFA] lg:w-[100vw] ">
        {/**login_section */}
        
      </main>

      <div className="lg:mt-0">
        <Footer />
      </div>
    </div>
  );
}
