import Head from "next/head";
import App from "./HomePage/App";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Mentor Connect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <App />
    </div>
  );
}
