import Head from 'next/head';
import Header from '../components/Header';
import ImpactCard from '../components/ImpactCard';
import MentorCard from '../components/MentorCard';
import Footer from '../components/Footer';


 export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Mentor Connect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      {/**Banner */}
      <main className="max-w-5xl mx-auto">
        <div className="mx-10 mt-6 mb-12 px-8 text-center border border-red-500 md:items-center md:mt-24">
          <h2 className="text-gray-800 font-bold text-4xl md:text-6xl border border-red-500 md:leading-tight">Encouraging industry growth & closing skills gap</h2>
          <h5 className="font-normal text-base pt-4 text-gray-light border border-red-500 md:font-bold md:text-2xl md:leading-7">Contributing to the future of upscaling world class professionals and industry players.</h5>

          <div className="flex flex-wrap justify-center gap-4 my-8 mx-auto">
            <a className="block w-full px-12 py-3 text-sm font-bold text-white bg-primary-700 rounded-lg shadow sm:w-auto active:bg-primary-700 hover:bg-primary-600 focus:outline-none focus:ring cursor-pointer" href="#">Find a Mentor</a>
            <a className="block w-full px-12 py-3 text-sm font-bold text-primary-700 rounded-lg shadow border border-gray-200 cursor-pointer sm:w-auto hover:text-primary-600 active:text-primary-700 focus:outline-none focus:ring" href="#">Become a Mentor</a>
          </div>
        </div>

        <div className="mb-24">
          <img className="object-cover h-[35rem] w-full lg:rounded-3xl"
            src="https://raw.githubusercontent.com/OSS-team-org/oss-frontend/main/public/hero.png"
            alt="Hero image" />
        </div>

      {/**Mentoring Stats */}
      <div className="mx-6 border border-red-500 md:my-48 ">
        <h3 className="flex items-center font-bold text-2xl md:text-5xl md:leading-tight">Mentoring is about the possibility of being the one who creates a spark in the brain that does.</h3>
        <div className="flex justify-around mt-8 md:justify-evenly">
          <div>
            <h5 className="text-2xl font-bold text-primary-600 md:text-5xl">120K+</h5>
            <p className="text-gray-light text-base md:text-xl font-bold md:pt-4">Mentees</p>
          </div>
          <div>
            <h5 className="text-2xl font-bold text-primary-600 md:text-5xl">32K+</h5>
            <p className="text-gray-light md:text-xl font-bold md:pt-4">Mentors</p>
          </div>
          <div>
            <h5 className="text-2xl font-bold text-primary-600 md:text-5xl">5.3M+</h5>
            <p className="text-gray-light md:text-xl font-bold md:pt-4">Sessions</p>
          </div>
        </div>
      </div>

      {/** Mentors */}
      <div className="mx-6">
        <h5 className="mt-24 font-bold text-2xl md:text-3xl">Mentors</h5>
        <p className="pt-2 md:text-base">World class professionals creating the spark in the lives of mentees.</p>
      </div>

      <div className="flex sm:snap-x snap-mandatory sm:overflow-scroll my-8 md:grid grid-cols-3 gap-6">
        <div className="snap-start">
          <MentorCard
            id=''
            image='/ivy.png'
            name='Ivy Barley'
            description='🇬🇭 Ghana - English, French +3more'
            title='Programs Manager - Microsoft'
            attributes='Career growth, Women empowerment'
          />
        </div>

        <div className="snap-start">
          <MentorCard
            id=''
            image='/jane.png'
            name='Jane Awuah'
            description='🇿🇦 South Africa - English, Swahili'
            title='Growth Manager - WorldCraft'
            attributes='Leadership, Growth, Women empowerment'
          />
        </div>

        <div className="snap-start">
          <MentorCard
            id=''
            image='/gifty.png'
            name='Gifty Johnson'
            description='🇰🇪 Kenya - English, Swahili, French'
            title='Snr. Software Engineer - MoneyStack'
            attributes='Software development, Mentorship, Job search'
          />
        </div>

        <div className="snap-start">
          <MentorCard
            id=''
            image='/gifty2.png'
            name='Gifty Johnson'
            description='🇰🇪 Kenya - English, Swahili, French'
            title='Snr. Software Engineer - MoneyStack'
            attributes='Software development, Mentorship, Job search'
          />
        </div>

        <div className="snap-start">
          <MentorCard
            id=''
            image='/gifty3.png'
            name='Gifty Johnson'
            description='🇰🇪 Kenya - English, Swahili, French'
            title='Snr. Software Engineer - MoneyStack'
            attributes='Software development, Mentorship, Job search'
          />
        </div>

        <div className="snap-start">
          <MentorCard
            id=''
            image='/gifty4.png'
            name='Gifty Johnson'
            description='🇰🇪 Kenya - English, Swahili, French'
            title='Snr. Software Engineer - MoneyStack'
            attributes='Software development, Mentorship, Job search'
          />
        </div>

        <div className="snap-start">
          <MentorCard
            id=''
            image='/gifty5.png'
            name='Gifty Johnson'
            description='🇰🇪 Kenya - English, Swahili, French'
            title='Snr. Software Engineer - MoneyStack'
            attributes='Software development, Mentorship, Job search'
          />
        </div>

        <div className="snap-start">
          <MentorCard
            id=''
            image='/gifty6.png'
            name='Gifty Johnson'
            description='🇰🇪 Kenya - English, Swahili, French'
            title='Snr. Software Engineer - MoneyStack'
            attributes='Software development, Mentorship, Job search'
          />
        </div>
      </div>

      <div className="flex flex-col justify-center items-center mb-4 px-6">
        <p className="text-xs font-semibold text-center text-gray-deep">Join 32K+ mentors creating sparks in lives of mentees.</p>
        <div className="flex flex-wrap justify-center gap-4 my-8 mx-auto">
          <a className="block w-full px-12 py-3 text-sm font-bold text-white bg-primary-700 rounded-lg shadow sm:w-auto active:bg-primary-700 hover:bg-primary-600 focus:outline-none focus:ring cursor-pointer" href="#">Become a Mentor</a>
        </div>
      </div>

      {/**Impacts on Mentees */}
      <div className="mt-24 px-6">
        <h5 className="text-2xl font-semibold pb-1">Impacts on Mentees</h5>
        <p className="text-base font-normal">World class professionals creating the spark in the lives of mentees.</p>
      </div>

      <div className="flex snap-x snap-mandatory sm:overflow-scroll pt-8 pb-12 md:grid grid-cols-3 gap-6">
        <div className="snap-start">
          <ImpactCard
            id=''
            image='/akosua.png'
            name='Akosua Adu-Gyamfi'
            spanDetails='🇬🇭 Ghana'
            details='English'
            spanName='Ivy Barley'
            content='is a great mentor. She was so willing to share her personal experience and career journey with me. And also shared resources to keep me accountable. Thanks!'
          />
        </div>

        <div className="snap-start">
          <ImpactCard
            id=''
            image='/akosua.png'
            name='Benjamin Blay'
            spanDetails='🇱🇷 Liberia'
            details='English'
            spanName='Gifty Johnson'
            content='is so selfless. She shared notes with me and took me through a interview mock session to help me prepare for ann interview. God bless and thank you!'
          />
        </div>

        <div className="snap-start">
          <ImpactCard
            id=''
            image='/akosua.png'
            name='Sarah Ma'
            spanDetails='🇱🇷 Liberia'
            details='English'
            spanName='Jane Awuah'
            content='is a kind lady! She took her time to explain what it means to be involved in tech and empowered me to be bold to incoperate or transition fully into tech with a business background.'
          />
        </div>

        <div className="snap-start">
          <ImpactCard
            id=''
            image='/akosua.png'
            name='Sarah Ma'
            spanDetails='🇱🇷 Liberia'
            details='English'
            spanName='Jane Awuah'
            content='is a kind lady! She took her time to explain what it means to be involved in tech and empowered me to be bold to incoperate or transition fully into tech with a business background.'
          />
        </div>

        <div className="snap-start">
          <ImpactCard
            id=''
            image='/akosua.png'
            name='Akosua Adu-Gyamfi'
            spanDetails='🇬🇭 Ghana'
            details='English'
            spanName='Ivy Barley'
            content='is a great mentor. She was so willing to share her personal experience and career journey with me. And also shared resources to keep me accountable. Thanks!'
          />
        </div>

        <div className="snap-start">
          <ImpactCard
            id=''
            image='/akosua.png'
            name='Benjamin Blay'
            spanDetails='🇱🇷 Liberia'
            details='English'
            spanName='Gifty Johnson'
            content='is so selfless. She shared notes with me and took me through a interview mock session to help me prepare for ann interview. God bless and thank you!'
          />
        </div>

        <div className="snap-start">
          <ImpactCard
            id=''
            image='/akosua.png'
            name='Sarah Ma'
            spanDetails='🇱🇷 Liberia'
            details='English'
            spanName='Jane Awuah'
            content='is a kind lady! She took her time to explain what it means to be involved in tech and empowered me to be bold to incoperate or transition fully into tech with a business background.'
          />
        </div>

        <div className="snap-start">
          <ImpactCard
            id=''
            image='/akosua.png'
            name='Sarah Ma'
            spanDetails='🇱🇷 Liberia'
            details='English'
            spanName='Jane Awuah'
            content='is a kind lady! She took her time to explain what it means to be involved in tech and empowered me to be bold to incoperate or transition fully into tech with a business background.'
          />
        </div>
      </div>

      <div className="flex flex-col justify-center items-center mb-4 px-6">
        <p className="text-xs font-semibold text-center text-gray-deep">Experience the impact from our 32K+ world class mentors</p>
        <div className="flex flex-wrap justify-center gap-4 my-8 mx-auto">
          <a className="block w-full px-12 py-3 text-sm font-bold text-white bg-primary-700 rounded-lg shadow sm:w-auto active:bg-primary-700 hover:bg-primary-600 focus:outline-none focus:ring cursor-pointer" href="#">Find a Mentor</a>
        </div>
      </div>

      <div className="mt-24 px-6">
        <h5 className="text-2xl font-semibold pb-1">Growth</h5>
        <p className="text-base font-normal">Some description about growth can go here</p>
      </div>

      <div className="flex">
        <img src="/growth.png" alt='' className="mt-8 w-full"/>
        <div className="flex justify-around mt-8">
          <div>
            <h5 className="text-2xl font-bold text-primary-600">120K+</h5>
            <p className="text-gray-light text-base">Mentees</p>
          </div>
          <div>
            <h5 className="text-2xl font-bold text-primary-600">32K+</h5>
            <p className="text-gray-light">Mentors</p>
          </div>
          <div>
            <h5 className="text-2xl font-bold text-primary-600">5.3M+</h5>
            <p className="text-gray-light">Sessions</p>
          </div>
        </div>
      </div>
      </main>

      <div className="mt-24">
        <Footer/>
      </div>
    </div>
  )
}
