import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header';


 export default function Home() {
  return (
    <div className="max-w-5xl mx-auto">
      <Head>
        <title>Mentor Connect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <h2 className="flex text-center items-center px-14 text-gray-800 font-bold text-4xl pt-4 border border-red-500 md:text-6xl md:">Encouraging industry growth & closing skills gap</h2>
      <h5 className="flex text-center font-normal text-base pt-4 px-14 text-gray-light border border-red-500  md:font-bold md:px-16">Contributing to the future of upscaling world class professionals and industry players.</h5>
        <div className="flex flex-col justify-center items-center py-12 px-6 border border-blue-500 md:flex-row">
          <button type="button" className="p-4 mb-4 text-sm font-bold text-white focus:outline-none bg-primary-700 rounded-lg hover:bg-primary-600 w-11/12 md:w-36 md:mr-8">Find a Mentor</button>
          <button type="button" className="p-4 text-sm font-bold text-primary-700 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 w-11/12 md:w-36">Become a mentor</button>
        </div>
          <img
            className="mt-2 flex items-center flex-grow w-80 h-full" 
            src='/hero.png' 
            alt='Hero'
          />
          <h3 className="flex items-center font-bold mt-24 mx-6 text-2xl md:text-4xl">Mentoring is about the possibility of being the one who creates a spark in the brain that does.</h3>
          <div className="flex justify-around items-center mt-8 gradient">
            <div>
              <h5 className="text-2xl font-bold bg-gradient-to-r from-lime-300 to-green-600">120K</h5>
              <p className="gray-light text-base">Mentees</p>
            </div>
            <div>
              <h5 className="text-2xl font-bold">32K</h5>
              <p className="gray-light">Mentors</p>
            </div>
            <div>
              <h5 className="text-2xl font-bold">5.3M</h5>
              <p className="gray-light">Sessions</p>
            </div>
          </div>
          <h5 className="mt-24 mx-6 font-bold text-2xl">Mentors</h5>
          <p className="mx-6 pt-2">World class professionals creating the spark in the lives of mentees.</p>
    </div>
  )
}
