import React, { useState } from "react";
import Head from "next/head";
import Header from "../components/homepage/Header";
import Footer from "../components/homepage/Footer";
import TabSwitch from "../components/mentor_profile/TabSwitch";
import { Education, Work_experience } from "../components/mentor_profile/tabInterfaces";



export default function Mentor_Profile() {
  const active: string =
    "border z-50  border-[0px] border-b-[7px] lg:border-b-[4px] border-[#5C7425] py-[10px] ease-in duration-75 delay-75";
  const activeText: string =
    "lg:text-[15px] text-[25px] font-extrabold  text-[#5C7425] ease-in duration-75 delay-75 ";
  const [Tags, setTags] = useState<Array<string>>([
    "Career growth",
    "Career advice",
    "Women empowerment ",
   /*  "Leadership",
    "Job Search",
    "Mentorship", */
  ]);
  const workExperiences: Work_experience[] = [
    {
      position: "Programs Manager",
      company: "Microsoft",
      first_year: "2019",
      last_year: "Present",
    },
    {
      position: "Founder",
      company: "Developers In Vogue",
      first_year: "2017",
      last_year: "Present",
    },
  ];
  const educational_info: Education[] = [
    {
      areaOfStudy: "MPhil Mathematical Statistics",
      school: "Kwame Nkrumah University Of Science and Technology",
      first_year: "2012",
      last_year: "2016",
    },
    {
      areaOfStudy: "Bachelors degree in Actuarial Science",
      school: "Kwame Nkrumah University Of Science and Technology",
      first_year: "2016",
      last_year: "2017",
    },
    {
      school: "Aburi Girls Senior High School",
      first_year: "2009",
      last_year: "2012",
    },
  ];
  const [description, setDescription] = useState<string>(
    "A Ghanaian entrepreneur, program manager and women in tech activist. I am a co-founder of Developers in Vogue, an organization that is paving the way for more African women to take up opportunities in the tech industry. In January 2022,... Show more"
  );
  const [Work_exp, setWork_exp] =
    useState<Array<Work_experience>>(workExperiences);
  const [Education, setEducation] =
    useState<Array<Education>>(educational_info);
  const [Tab, setTab] = useState<string>("About");

  return (
    <div className="!overflow-x-hidden">
      <Head>
        <title>Profile </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header navTitle="MentorConnect" />

      {/**Banner */}
      <main className=" w-[100vw] lg:w-[100vw]  border-red-500 ">
        {/**Profile_picture_section */}
        <div className="   border-yellow-500  flex flex-col lg:flex-row items-center justify-around lg:justify-between h-[auto] lg:items-stretch lg:h-[100%]">
          <div className="  border-blue-700 my-[20px] lg:m-[0]   w-[90vw] lg:w-[35%] flex justify-center items-center   h-[50vh] lg:h-[auto]" >
            <img
              className="object-cover lg:min-h-[100%]  h-[90%] w-[100%] rounded-2xl lg:rounded-[0]  "
              src="/ivy_large.png"
              alt="Hero image"
            />
          </div>
          <div className="flex flex-col items-center lg:items-start justify-start   border-blue-0 lg:!w-[64%]">
          <div className="flex flex-col items-center lg:items-start    border-blue-200 lg:pl-[0px] justify-between lg:justify-evenly  border-pink-0 w-[60%] min-h-[150px] lg:min-h-[120px] lg:min-w-[98%]  mb-[50px] lg:mb-[0]">
            <div className="  border-blue-200 lg:w-[100%] flex lg:flex-row lg:justify-between lg:items-center">
            <div className="lg:text-[18px] text-3xl text-[#333333] font-extrabold ">
   
              Ivy Barley
            </div>
            
            <div className="hidden lg:flex w-[150px] h-[50px] flex flex-row justify-center items-center border border-pink-200 bg-primary-700 rounded-lg shadow  active:bg-primary-700 hover:bg-primary-600 focus:outline-none focus:ring cursor-pointer text-[bold] ">
              <div className="text-[white]">Book A Session</div>
            </div>
           
            </div>
            
            <div className="lg:text-[15px] text-[22px] text-center text-[#333333] font-bold ">
              Programs Manager - Microsoft
            </div>
            <div className="lg:text-[15px] flex lg:!ml-[0px]  justify-around lg:justify-between   border-red-100 w-[100%] lg:w-[25%] text-[25px] lg:mx-[0] !mx-[-35px] lg:m-0">
              <div>Ghana</div> <div>languages +3more</div>
            </div>
          </div>

          <div className="grid grid-cols-3  border-pink-0 w-[90%] lg:w-[68%] h-[auto] gap-x-1  gap-y-5 lg:gap-y-2 p-2  mb-[50px] lg:mb-[10px] lg:pl-[0px] ">
            {Tags?.map((tag, i) => {
              return (
                <div className=" border  border-[#D8D3E3]-0 rounded-3xl lg:h-[28px] h-[45px] lg:min-w-[10px] w-[auto] text-[#3D2574] font-bold lg:font-semibold flex flex-col justify-items-center items-center">
                  <span className=" flex flex-col justify-center text-[16px] lg:text-[12px] grow">
                    {tag}
                  </span>
                </div>
              );
            })}
          </div>
          <div className="flex lg:hidden  border-pink-0 w-[90%] h-[auto] gap-[4px] justify-center mb-[50px]">
            <a
              className="  flex justify-center items-center  w-[100%] px-12 py-3  text-2xl xs:!text-[250px] h-[65px] font-bold text-white bg-primary-700 rounded-lg shadow  active:bg-primary-700 hover:bg-primary-600 focus:outline-none focus:ring cursor-pointer"
              href="#"
            >
              Book a session
            </a>
          </div>
           {/* Tab section */}
        <div className="w-[100%] lg:w-[90%] flex justify-center lg:justify-start mb-[-5px] lg:mb-[-13px] lg:pl-[0px] ">
          {/* Tab Titles */}
          <div className="flex   justify-between lg:w-[40%] w-[90%] h-[70px] items-center lg:px-[0] px-[10px]">
            <div
              onClick={() => setTab("About")}
              className={Tab == "About" ? active : ""}
            >
              <span
                className={
                  Tab == "About"
                    ? activeText
                    : "lg:text-[15px] text-2xl ease-in duration-75 delay-75 cursor-pointer"
                }
              >
                About 
              </span>
            </div>
            <div
              onClick={() => setTab("work_experience")}
              className={
                Tab == "work_experience"
                  ? active
                  : "lg:text-[10px] text-2xl ease-in duration-75 delay-75 cursor-pointer"
              }
            >
              <span
                className={
                  Tab == "work_experience"
                    ? activeText
                    : "lg:text-[15px] text-2xl ease-in duration-75 delay-75 cursor-pointer"
                }
              >
                Work experience
              </span>
            </div>
            <div
              onClick={() => setTab("education")}
              className={Tab == "education" ? active : ""}
            >
              <span className={Tab == "education" ? activeText : " lg:text-[15px] text-2xl cursor-pointer"}>
                Education
              </span>
            </div>
          </div>
        </div>
        <div className=" border-b-0 border-t-2 border-pink-0 w-[auto] lg:w-[100%] h-[auto] flex flex-center">
          <TabSwitch  
            title={Tab}
            description={description}
            education={Education}
            work_experience={Work_exp}
          />
         
        </div>
          </div>
          
         
        </div>

       
      </main>

      <div className="mt-24 lg:mt-0">
        <Footer />
      </div>
    </div>
  );
}
